# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://louyuestar.github.io
date_format: "ordinal"
title: AIF
subtitle: "打码改变人生"
description: "娄跃的个人博客"
keywords: AIF, Yue Lou, mzlogin, louyue
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Yue Lou
organization: 
organization_url: 
github_username: louyuestar
location: nanjing, China
email: louyue@asiainfo.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: louyuestar/louyuestar.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: louyuestar
    repo: louyuestar.github.io
    oauth:
        client_id: ce9bfd900f345bbc21e2
        client_secret: 1dccfb9349dce5bc0d64c87246a6c5f43c4d2ffa
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: louyuestar
    repo: louyuestar.github.io
    clientID: ce9bfd900f345bbc21e2
    clientSecret: 1dccfb9349dce5bc0d64c87246a6c5f43c4d2ffa
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

theme: jekyll-theme-cayman